medium_blog_post_optimization:
  description: >
    Enhance the blog post for Medium publication by ensuring high readability and alignment with Medium's formatting guidelines.
    Focus on improving structure, visual appeal, and SEO optimization, while ensuring the content maintains a conversational tone and is optimized for reader engagement.
    Key tasks include:
    - Structure the content for readability (headings, subheadings, paragraphs, bullet points)
    - Ensure text aligns with readability guidelines (e.g., Hemingway app standards, active voice, short sentences)
    - Suggest subtle calls to action for reader engagement and potential monetization
  expected_output: >
    A fully optimized and polished Medium-ready blog post that:
    - Has a clear structure with appropriate headings, subheadings, and formatting
    - Contains a maximum of 5 image placeholders with concise descriptions
    - Is highly readable with simple language, a clear tone, and engaging style
    - Contains subtle calls to action to boost reader engagement and monetization potential
  async_execution: false
  agent: medium_optimization_specialist

tagging_and_monetization_enhancement:
  description: >
    Suggest the most effective tags for the blog post to maximize its reach on Medium and optimize it for monetization.
    The goal is to increase visibility and engagement through well-researched tags.
    Ensure that all suggestions align with Medium’s best practices for the Partner Program.
  expected_output: >
    A set of 5 optimized tags relevant to the blog post's content.
  async_execution: false
  agent: tag_optimization_specialist

image_placement_task:
  description: >
    Review the final blog post and suggest appropriate locations for a maximum of five realistic images to enhance reader engagement. Focus on using images that are relevant and visually appealing to decorate the post, such as photographs of real-world scenes, people, nature, or urban environments mentioned in the content. Distribute the images wisely throughout the post to maintain visual interest. Ensure that no charts, graphs, or statistical images are included, as there is no real data available for these. Provide a short description for each suggested image that aligns well with the content and style.
  expected_output: >
    A version of the blog post with image placeholders and descriptions, formatted as "[Pic1: Description of the required image]". The descriptions should be concise and specify what the image should represent, such as "[Pic1: A vibrant cityscape during sunset]" or "[Pic2: People collaborating in a modern office environment]".
  async_execution: false
  agent: image_placement_expert